# Generated by Django 4.2.2 on 2023-06-22 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(help_text='Zadejte typ motoru vozidla - např. spalovací, elektro', max_length=50, verbose_name='Typ motoru')),
                ('etype', models.CharField(blank=True, help_text='Zadejte specifikace motoru vozidla - např. dvouválec, objem', max_length=100, null=True, verbose_name='Bližší specifikace motoru')),
                ('doors', models.PositiveIntegerField(default=5, help_text='Zadejte číslo odpovídající k počtu dveří vozidla', verbose_name='Počet dveří vozidla')),
            ],
            options={
                'verbose_name': 'Typ',
                'verbose_name_plural': 'Typy',
                'ordering': ['-doors'],
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cars_capacity', models.PositiveIntegerField(default=10, help_text='Zadejte maximální kapacitu prodejny', verbose_name='Kapacita prodejny')),
                ('city', models.CharField(help_text='Zadejte název obce', max_length=80, verbose_name='Město')),
                ('street', models.CharField(help_text='Zadejte název ulice + číslo', max_length=80, verbose_name='Ulice')),
                ('psc', models.PositiveIntegerField(blank=True, help_text='Zadejte poštovní směrovací číslo', null=True, verbose_name='PSČ')),
            ],
            options={
                'verbose_name': 'Prodejna',
                'verbose_name_plural': 'Prodejny',
                'ordering': ['-cars_capacity'],
            },
        ),
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='Zadejte roli zákazníka - např. prodávající, nakupující', max_length=80, verbose_name='Role zákazníka')),
                ('note', models.TextField(blank=True, help_text='Zadejte poznámku k zákazníkovi', max_length=100, null=True, verbose_name='Poznámka')),
            ],
            options={
                'verbose_name': 'Zákazník',
                'verbose_name_plural': 'Zákazníci',
            },
        ),
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Zadejte značku auta - např. Škoda Octavia, Audi quattro', max_length=60, verbose_name='Značka vozidla')),
                ('y_of_manufacture', models.PositiveIntegerField(blank=True, help_text='Zadejte rok výroby auta', null=True, verbose_name='Rok výroby')),
                ('mileage', models.FloatField(help_text='Zadejte počet najetých km vozidla', verbose_name='Počet najetých km')),
                ('price', models.FloatField(help_text='Zadejte cenu auta', verbose_name='Cena')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zapasnici.gender', verbose_name='Typ')),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zapasnici.organisation', verbose_name='Prodejna')),
            ],
            options={
                'verbose_name': 'Auto',
                'verbose_name_plural': 'Auta',
                'ordering': ['-price'],
            },
        ),
    ]
