# Generated by Django 4.2.2 on 2023-06-22 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zapasnici', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_type', models.CharField(help_text='Zadejte typ pohlaví - např: finanční, reklamní, promo', max_length=50, verbose_name='Typ podpory')),
                ('support_text', models.CharField(blank=True, help_text='Blizší specifikace Vašeho představujícího se partnerství', max_length=200, null=True, verbose_name='Bližší specifikace sponzorství')),
                ('support_money', models.PositiveIntegerField(default=5, help_text='Zadejte představující finanční obnos', verbose_name='Finanční částka')),
            ],
            options={
                'verbose_name': 'Sponzoři',
                'verbose_name_plural': 'Sponzoři',
                'ordering': ['-support_money'],
            },
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='gender',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.AddField(
            model_name='fighter',
            name='sponsors',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='zapasnici.sponsors', verbose_name='Sponzoři'),
            preserve_default=False,
        ),
    ]
