# Generated by Django 4.2.2 on 2023-06-22 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapasnici', '0002_sponsors_remove_fighter_gender_delete_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ['-organisation_year'], 'verbose_name': 'Organizace', 'verbose_name_plural': 'Organizace'},
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='street',
            new_name='organisation_NetWorth',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='cars_capacity',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='psc',
        ),
        migrations.AddField(
            model_name='organisation',
            name='organisation_Median_popularity',
            field=models.PositiveIntegerField(default=10, help_text='Zadejte, medián počtu návštěvnosti organizace', verbose_name='Popularita'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='organisation_residence',
            field=models.CharField(default=1000, help_text='Zadejte, kde organizace sídlí', max_length=80, verbose_name='Sídlo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisation',
            name='organisation_year',
            field=models.PositiveIntegerField(default=10, help_text='Zadejte rok založení organizace', verbose_name='Rok'),
        ),
    ]
