# Generated by Django 4.2.2 on 2023-06-22 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zapasnici', '0003_alter_organisation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fighter',
            options={'ordering': ['-figher_networth'], 'verbose_name': 'Zápasník', 'verbose_name_plural': 'Zápasníci'},
        ),
        migrations.AlterModelOptions(
            name='tournaments',
            options={'verbose_name': 'Turnaj', 'verbose_name_plural': 'Turnaje'},
        ),
        migrations.RenameField(
            model_name='fighter',
            old_name='brand',
            new_name='Fighter_id',
        ),
        migrations.RenameField(
            model_name='fighter',
            old_name='sponsors',
            new_name='fighter_sponsors',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='mileage',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='price',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='y_of_manufacture',
        ),
        migrations.RemoveField(
            model_name='tournaments',
            name='note',
        ),
        migrations.RemoveField(
            model_name='tournaments',
            name='role',
        ),
        migrations.AddField(
            model_name='fighter',
            name='figher_networth',
            field=models.FloatField(default=10000, help_text='Finanční kapitál', verbose_name='Celkové jmění'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fighter',
            name='fighter_fighting_year',
            field=models.PositiveIntegerField(blank=True, help_text='Počet let, od započatí tréninku', null=True, verbose_name='Celkové počet let'),
        ),
        migrations.AddField(
            model_name='fighter',
            name='fighter_organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zapasnici.organisation', verbose_name='Organizace'),
        ),
        migrations.AddField(
            model_name='fighter',
            name='fighter_year',
            field=models.FloatField(default=50, help_text='Věk zápasníka', verbose_name='Věk'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournaments',
            name='tournament_description',
            field=models.TextField(blank=True, help_text='Popis Turnaje', max_length=100, null=True, verbose_name='Turnaj'),
        ),
        migrations.AddField(
            model_name='tournaments',
            name='tournament_id',
            field=models.CharField(default=5, help_text='Popis turnaje', max_length=80, verbose_name='Turnaj'),
            preserve_default=False,
        ),
    ]
