# Generated by Django 4.2.2 on 2023-06-22 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapasnici', '0004_alter_fighter_options_alter_tournaments_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsors',
            name='support_money',
            field=models.FloatField(default=10, help_text='Zadejte představující finanční obnos', verbose_name='Finanční částka'),
        ),
    ]
