# Generated by Django 4.2.2 on 2023-06-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapasnici', '0007_fighter_fighter_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='Fighter_Country',
            field=models.CharField(help_text='Země odkud zápasník pochází - kde byl narozen', max_length=60, null=True, verbose_name='Země'),
        ),
        migrations.AddField(
            model_name='fighter',
            name='Fighter_Height',
            field=models.PositiveIntegerField(default=180, max_length=3, verbose_name='Výška zápasníka v cm'),
        ),
        migrations.AddField(
            model_name='fighter',
            name='Fighter_Weight',
            field=models.FloatField(default=82.5, max_length=3, verbose_name='Váha zápasníka v Kg'),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='Fighter_id',
            field=models.CharField(max_length=60, null=True, verbose_name='Jméno a příjmení'),
        ),
    ]
