# Generated by Django 4.2.2 on 2023-06-22 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapasnici', '0008_fighter_fighter_country_fighter_fighter_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='organisation_logo',
            field=models.ImageField(blank=True, null=True, upload_to='Photo/Organizace/'),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='Fighter_Height',
            field=models.PositiveIntegerField(default=180, max_length=3, null=True, verbose_name='Výška zápasníka v cm'),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='Fighter_photo',
            field=models.ImageField(blank=True, null=True, upload_to='Photo/Zapasnici/'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation_residence',
            field=models.CharField(help_text='Zadejte, kde organizace sídlí - Země, Město', max_length=80, null=True, verbose_name='Sídlo'),
        ),
        migrations.AlterField(
            model_name='sponsors',
            name='support_type',
            field=models.CharField(help_text='Zadejte typ pohlaví - např: finanční, reklamní, promo', max_length=50, null=True, verbose_name='Typ podpory'),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='tournament_id',
            field=models.CharField(help_text='Název turnaje/akce/id', max_length=80, null=True, verbose_name='Turnaj'),
        ),
    ]
