# Generated by Django 4.2.2 on 2023-06-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapasnici', '0009_organisation_organisation_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='organisation_Median_popularity',
        ),
        migrations.AddField(
            model_name='organisation',
            name='organisation_Average_payperview',
            field=models.PositiveIntegerField(blank=True, help_text='Největší počet prodaných payperview', null=True, verbose_name='Popularita'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='organisation_average_popularity',
            field=models.PositiveIntegerField(blank=True, help_text='Průměrný počet návštěvnosti organizace', null=True, verbose_name='Popularita'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='organisation_owner',
            field=models.CharField(help_text='Zadejte, vlastníka/y organizace', max_length=80, null=True, verbose_name='Vlastník'),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='Fighter_Height',
            field=models.PositiveIntegerField(blank=True, default=180, max_length=3, verbose_name='Výška zápasníka v cm'),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='Fighter_Weight',
            field=models.FloatField(blank=True, default=82.5, max_length=3, verbose_name='Váha zápasníka v Kg'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation_Max_popularity',
            field=models.PositiveIntegerField(blank=True, help_text='Zadejte, Největší návštěvnost organizace', null=True, verbose_name='Popularita'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation_NetWorth',
            field=models.FloatField(blank=True, default=100000, help_text='NetWorth v $', verbose_name='NetWorth'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation_residence',
            field=models.CharField(help_text='Kde organizace sídlí - Země, Město', max_length=80, null=True, verbose_name='Sídlo'),
        ),
        migrations.AlterField(
            model_name='sponsors',
            name='support_money',
            field=models.FloatField(blank=True, help_text='Finanční částka v $', null=True, verbose_name='Finanční částka'),
        ),
    ]
