# Generated by Django 4.2.2 on 2023-06-22 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapasnici', '0011_organisation_organisation_max_payperview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='organisation_Average_payperview',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='organisation_Max_payperview',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='organisation_average_popularity',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation_NetWorth',
            field=models.FloatField(blank=True, help_text='NetWorth v $', null=True, verbose_name='NetWorth'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation_owner',
            field=models.CharField(max_length=80, null=True, verbose_name='Prezident/ředitel'),
        ),
    ]
