# Generated by Django 4.2.2 on 2023-06-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapasnici', '0012_remove_organisation_organisation_average_payperview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='organisation_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Zadejte název společnosti'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation_residence',
            field=models.CharField(help_text='Kde organizace sídlí - Země', max_length=80, null=True, verbose_name='Sídlo'),
        ),
    ]
