# Generated by Django 4.2.2 on 2023-06-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapasnici', '0013_organisation_organisation_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='organisation_NetWorth',
        ),
        migrations.AddField(
            model_name='organisation',
            name='organisation_short',
            field=models.CharField(max_length=100, null=True, verbose_name='Zadejte zkratku společnosti'),
        ),
    ]
