# Generated by Django 4.2.2 on 2023-06-22 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zapasnici', '0016_alter_organisation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsors',
            options={'ordering': ['-support_id'], 'verbose_name': 'Sponzoři', 'verbose_name_plural': 'Sponzoři'},
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='organisation_fkey',
            new_name='organisation_highest',
        ),
        migrations.RemoveField(
            model_name='sponsors',
            name='support_money',
        ),
        migrations.RemoveField(
            model_name='sponsors',
            name='support_type',
        ),
        migrations.AddField(
            model_name='organisation',
            name='organisation_support',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zapasnici.sponsors', verbose_name='Sponzoři'),
        ),
        migrations.AddField(
            model_name='sponsors',
            name='support_id',
            field=models.CharField(max_length=50, null=True, verbose_name='Název'),
        ),
        migrations.AddField(
            model_name='sponsors',
            name='support_logo',
            field=models.ImageField(blank=True, null=True, upload_to='Photo/Sponzori/'),
        ),
        migrations.AlterField(
            model_name='sponsors',
            name='support_text',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Bližší specifikace firmy'),
        ),
    ]
