# Generated by Django 4.2.2 on 2023-06-22 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapasnici', '0017_alter_sponsors_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='organisation_support_money',
            field=models.FloatField(blank=True, max_length=10, null=True, verbose_name='Hodnota smlouvy za rok v $'),
        ),
    ]
