# Generated by Django 4.2.2 on 2023-06-22 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zapasnici', '0018_organisation_organisation_support_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='organisation_support_money',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation_support',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zapasnici.sponsors', verbose_name='Největší sponzor'),
        ),
    ]
