# Generated by Django 4.2.2 on 2023-06-22 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zapasnici', '0019_remove_organisation_organisation_support_money_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fighter',
            name='fighter_sponsors',
        ),
    ]
